// Code generated by "stringer -type=EventKind"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventJoin-0]
	_ = x[EventHealthy-1]
	_ = x[EventSuspect-2]
	_ = x[EventFaulty-3]
	_ = x[EventLeft-4]
	_ = x[EventAlive-5]
	_ = x[EventWrap-6]
}

const _EventKind_name = "EventJoinEventHealthyEventSuspectEventFaultyEventLeftEventAliveEventWrap"

var _EventKind_index = [...]uint8{0, 9, 21, 33, 44, 53, 63, 72}

func (i EventKind) String() string {
	if i >= EventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
