package proto

import "github.com/heyvito/eswim/internal/fsm"

// IndirectPing represents a request sent by a member suspecting that another
// member is faulty.
type IndirectPing struct {
	// Cookie is a random value generated by the requester to identify this ping
	// request. It must be relayed back as is to it.
	Cookie uint16

	// Period represents the protocol period in which the host was when sending
	// this request. It must be relayed back as is to it.
	Period uint16

	// Address represents the address to perform a ping against.
	Address IP
}

func (i IndirectPing) OpCode() OpCode { return IING }

func (i IndirectPing) RequiredSize() int { return 5 + i.Address.Size() }

func (i IndirectPing) Encode(into []byte) {
	newWriter(into).
		u8(byte(i.Address.AddressKind)).
		u16(i.Cookie).
		u16(i.Period).
		ip(i.Address)
}

// fsmStates: indirectPingDecoder flags, cookie, period, address

type indirectPingDecoderState uint8

const (
	indirectPingDecoderStateFlags indirectPingDecoderState = iota
	indirectPingDecoderStateCookie
	indirectPingDecoderStatePeriod
	indirectPingDecoderStateAddress
)

// fsmStatesEnd

var indirectPingDecoder = fsm.Def[IndirectPing, indirectPingDecoderState, struct{}]{
	InitialSize: 1,
	Feed: func(f *fsm.FSM[IndirectPing, indirectPingDecoderState, struct{}], state indirectPingDecoderState, ctx *struct{}, b byte) error {
		switch state {
		case indirectPingDecoderStateFlags:
			f.Value.Address.AddressKind = AddressKind(b)
			f.TransitionSatisfySize(indirectPingDecoderStateCookie, 2)
		case indirectPingDecoderStateCookie:
			f.Value.Cookie = f.U16()
			f.TransitionSatisfySize(indirectPingDecoderStatePeriod, 2)
		case indirectPingDecoderStatePeriod:
			f.Value.Period = f.U16()
			f.TransitionSatisfySize(indirectPingDecoderStateAddress, f.Value.Address.Size())
		case indirectPingDecoderStateAddress:
			fsmCopyIP(f, &f.Value.Address)
			return fsm.Done
		}

		return nil
	},
}
