// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BTRP-1]
	_ = x[BTRR-2]
	_ = x[BTRA-3]
	_ = x[PING-4]
	_ = x[PONG-5]
	_ = x[IING-6]
	_ = x[IONG-7]
	_ = x[SYNC-8]
}

const _OpCode_name = "BTRPBTRRBTRAPINGPONGIINGIONGSYNC"

var _OpCode_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32}

func (i OpCode) String() string {
	i -= 1
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
