// Code generated by "stringer -type=SyncMode"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SyncModeFirstPhase-0]
	_ = x[SyncModeSecondPhase-1]
	_ = x[SyncModeBootstrap-2]
	_ = x[SyncModeBootstrapAck-3]
}

const _SyncMode_name = "SyncModeFirstPhaseSyncModeSecondPhaseSyncModeBootstrapSyncModeBootstrapAck"

var _SyncMode_index = [...]uint8{0, 18, 37, 54, 74}

func (i SyncMode) String() string {
	if i >= SyncMode(len(_SyncMode_index)-1) {
		return "SyncMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SyncMode_name[_SyncMode_index[i]:_SyncMode_index[i+1]]
}
