// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeTypeStable-1]
	_ = x[NodeTypeSuspect-2]
	_ = x[NodeTypeRemote-4]
	_ = x[NodeTypeInvalid-0]
}

const (
	_NodeType_name_0 = "NodeTypeInvalidNodeTypeStableNodeTypeSuspect"
	_NodeType_name_1 = "NodeTypeRemote"
)

var (
	_NodeType_index_0 = [...]uint8{0, 15, 29, 44}
)

func (i NodeType) String() string {
	switch {
	case i <= 2:
		return _NodeType_name_0[_NodeType_index_0[i]:_NodeType_index_0[i+1]]
	case i == 4:
		return _NodeType_name_1
	default:
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
